#!/usr/bin/env bash
# Prina OSS installer — generates .env (random secrets), starts the stack, waits for health.
# Lightweight variant of the commercial kit installer: no license, no registry login.
# Idempotent: an existing .env is never overwritten.
set -euo pipefail

say()  { printf '\033[1;34m[prina]\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31m[prina]\033[0m %s\n' "$*" >&2; exit 1; }

cd "$(dirname "$0")"

# 0) prerequisites
command -v docker >/dev/null 2>&1 || fail "docker not found — see https://docs.docker.com/engine/install/ and retry."
docker compose version >/dev/null 2>&1 || fail "docker compose (v2 plugin) not found."
docker info >/dev/null 2>&1 || fail "cannot reach the docker daemon (check permissions or service status)."

# 1) generate .env (only if absent — passwords are random)
if [ ! -f .env ]; then
  VERSION="${PRINA_VERSION:-}"
  if [ -z "$VERSION" ]; then
    read -r -p "[prina] version to install (e.g. 0.3.0): " VERSION
    [ -n "$VERSION" ] || fail "a version tag is required — see https://github.com/humanetools/prina/releases"
  fi
  rand() { head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; }
  cat > .env <<EOF
# Prina OSS configuration — generated by install.sh (passwords are random)
PRINA_VERSION=$VERSION
PRINA_PORT=3000

POSTGRES_USER=prina
POSTGRES_PASSWORD=$(rand 16)
POSTGRES_DB=prina

S3_BUCKET=prina-assets
S3_ACCESS_KEY=prina
S3_SECRET_KEY=$(rand 16)

IMGPROXY_KEY=$(rand 32)
IMGPROXY_SALT=$(rand 32)

LOG_LEVEL=info
EOF
  chmod 600 .env
  say ".env created (version $VERSION)"
else
  say "using existing .env (not overwritten)"
fi

set -a; . ./.env; set +a
PRINA_PORT="${PRINA_PORT:-3000}"

# 2) port conflict check — only asks when there is a conflict
port_busy() { (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null && { exec 3>&-; return 0; } || return 1; }
if port_busy "$PRINA_PORT"; then
  if docker compose ps --format '{{.Service}}' 2>/dev/null | grep -q '^core$'; then
    say "port $PRINA_PORT — already used by an existing Prina stack (assuming re-run, continuing)."
  else
    say "port $PRINA_PORT is already in use."
    read -r -p "[prina] alternative port (enter = 3300): " NEWPORT
    NEWPORT="${NEWPORT:-3300}"
    sed -i.bak "s/^PRINA_PORT=.*/PRINA_PORT=$NEWPORT/" .env && rm -f .env.bak
    PRINA_PORT="$NEWPORT"
    say "changed PRINA_PORT to $PRINA_PORT."
  fi
fi

# 3) start
say "pulling images… (version ${PRINA_VERSION:-?})"
docker compose pull -q
say "starting the stack…"
docker compose up -d

# 4) wait for health (up to 120s)
say "waiting for core…"
for i in $(seq 1 40); do
  if command -v curl >/dev/null 2>&1; then
    body=$(curl -sf "http://localhost:$PRINA_PORT/health" 2>/dev/null || true)
  else
    body=$(wget -qO- "http://localhost:$PRINA_PORT/health" 2>/dev/null || true)
  fi
  if printf '%s' "$body" | grep -q '"status":"ok"'; then
    say "installed! open the setup wizard in your browser:"
    printf '\n    \033[1mhttp://localhost:%s/admin\033[0m\n\n' "$PRINA_PORT"
    say "(on a remote server, replace localhost with the server address)"
    say "update: change PRINA_VERSION in .env, then: docker compose pull && docker compose up -d"
    exit 0
  fi
  sleep 3
done

printf '\033[1;31m[prina]\033[0m core did not become healthy within 120s. Recent logs:\n' >&2
docker compose logs core --tail 30 >&2 || true
exit 1
